/**
 * USER MOMENTS STORE — Completely independent from milestones.
 * Storage key: USER_MOMENTS_{pregnancyId}
 * Handles ONLY user-created moments. Never shares state with milestones.
 */
import { loadJSON, saveJSON } from './storage';
import { Moment, MomentOrigin } from '../types/pregnancy';

const STORAGE_PREFIX = 'USER_MOMENTS_';

function storageKey(pregnancyId: string): string {
  return `${STORAGE_PREFIX}${pregnancyId}`;
}

/** Remove any object that is NOT a valid manual/milestone moment. Migration cleanup. */
export function cleanMoments(raw: unknown[]): Moment[] {
  const cleaned: Moment[] = [];
  for (const item of raw) {
    const o = item as Record<string, unknown> | null;
    if (!o || typeof o !== 'object') continue;
    if (o.type === 'milestone') continue;
    if ('milestoneDate' in o || o.autoGenerated === true) continue;
    if (typeof o.title === 'string' && /Days to Go/i.test(o.title)) continue;
    if ('milestoneId' in o && !('createdAt' in o)) continue;
    if (o.type === 'moment' || ('createdAt' in o && !('milestoneDate' in o))) {
      const origin = (o.origin === 'manual' || o.origin === 'milestone' ? o.origin : 'manual') as MomentOrigin;
      cleaned.push({
        id: String(o.id ?? `moment-${Date.now()}-${Math.random()}`),
        type: 'moment',
        origin,
        title: String(o.title ?? o.note ?? o.text ?? 'Moment'),
        note: o.note ?? o.text,
        imageUri: o.imageUri ?? null,
        createdAt: String(o.createdAt ?? o.date ?? new Date().toISOString()),
        linkedMilestoneId: o.linkedMilestoneId ?? o.milestoneId,
      } as Moment);
    }
  }
  return cleaned;
}

const LEGACY_KEY = (id: string) => `mommy_moments_${id}`;

export async function loadMoments(pregnancyId: string): Promise<Moment[]> {
  let raw = await loadJSON<unknown[]>(storageKey(pregnancyId));
  if ((!raw || !Array.isArray(raw)) && pregnancyId) {
    raw = await loadJSON<unknown[]>(LEGACY_KEY(pregnancyId));
  }
  if (!raw || !Array.isArray(raw)) return [];
  const cleaned = cleanMoments(raw);
  if (__DEV__ && cleaned.length !== raw.length) {
    console.warn('[MomentsStore] Migration: removed', raw.length - cleaned.length, 'non-moment objects');
  }
  return cleaned;
}

export async function saveMoments(pregnancyId: string, moments: Moment[]): Promise<void> {
  await saveJSON(storageKey(pregnancyId), moments);
}

/** Runtime guard: remove any milestone-like object from array. */
export function validateMomentsOnly(moments: Moment[]): Moment[] {
  const valid = moments.filter((m) => {
    if (m.type !== 'moment') {
      if (__DEV__) console.error('[MomentsStore] GUARD: Removed non-moment from moments[]:', m);
      return false;
    }
    return true;
  });
  return valid;
}
